### ISSUE TITLE
When hovering over file tabs, the mouse visual should be a pointer, not a grab

### ISSUE THREAD

**Issue by mark-juicemind** [JuiceMind/JuiceMind#103]
![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/619c1b4d-3f3e-4b6b-a9d8-ea28ec639592) ![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/be48017f-ccb3-4bc5-836b-79dcdf8032e9)

The mouse should turn into a "grab" only when dragging a file

**Comment by Guido-Ferraro** [comment]
@mark-juicemind do you mean it should be `pointer` (right) or `default` (left)? (See image)
![Image](https://github.com/JuiceMind/JuiceMind/assets/82129814/9b694a2c-e514-4e89-9eb1-d1232b267d7d)

---

Consider that the cursor currently switches from `grab` (on hover) to `grabbing` (dragging):
![Image](https://github.com/JuiceMind/JuiceMind/assets/82129814/e60d9e3b-ca32-443f-a827-bbfe94a35aed)
