### ISSUE TITLE
When changing project type, there should be a warning that all contents will be lost

### ISSUE THREAD

**Issue by mark-juicemind** [JuiceMind/JuiceMind#104]
Or even better would be to save the current state of all projects that have been worked on. For example, if i work on Java and then switch to Python and do some work there, and then switch back to Java, all of the work I did on Java should be saved. When I switch back to Python, all of the work I did on python should be saved.

**Comment by juicemind-dev** [comment]
Fixing https://github.com/JuiceMind/JuiceMind/issues/13 will complete this task

**Comment by mark-juicemind** [comment]
Have you removed the option to change project types after making an IDE?
