### ISSUE TITLE
Students have access to "mcq", "short answer" teacher options

### ISSUE THREAD

**Issue by mark-juicemind** [JuiceMind/JuiceMind#133]
![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/a8ea621c-dfc9-4904-9178-562ba472e61a)

![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/6b9ce488-8513-4696-8c21-3c66c4c7a168)

![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/6c67c901-26f3-4a1e-9e58-1066b01fb542)

**Comment by juicemind-dev** [comment]
This was because of short answer and MCQ. Both views fixed.
