### ISSUE TITLE
Short answer has no settings

### ISSUE THREAD

**Issue by mark-juicemind** [JuiceMind/JuiceMind#134]
![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/f33f93d3-329c-4a5d-9c11-80b7add7649d)

**Comment by juicemind-dev** [comment]
Include all the settings that CodingRooms has

**Comment by guido-ferraro** [comment]
Ignore Hide Grades settings for coding rooms has no defined functionality so it isn't included in the PR. Needs specification.

Instant Feedback PR runs a simple not empty check to prevent an empty submit. If tempate and answer are equal, the student gets 0 points. Else, the student gets total points.
