### ISSUE TITLE
Columns not working?

### ISSUE THREAD

**Issue by mark-juicemind** [JuiceMind/JuiceMind#135]
![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/dfbeb9d4-a22a-4864-84cd-9d561d07e698)

Clicking the columns icons at the top doesn't do anything it seems.

**Comment by juicemind-dev** [comment]
Which component gives you this? Text component should not give option for columns.

**Comment by juicemind-dev** [comment]
Fixed by removing the columns component
