### ISSUE TITLE
Copying or duplicating Teams and lessons

### ISSUE THREAD

**Issue by ianj0710** [JuiceMind/JuiceMind#149]
When we create a Team for different classes it would be great if we could then duplicate sections/or lessons from within that Team to other teams we have set up. Much like the Reuse Post option in Google Classroom. 

-------------------------------------------------------
SK: 
Hi - I asked the other day about multiple sessions of one block of content. Pretty sure the answer revolved around how to copy a project from one block of content to another. Can you look at the pic I've attached? Is there any way to work like that?

**Comment by juicemind-dev** [comment]
Hi @ianj0710 !

Yes, we're in the process of adding this feature. Here is the link to the issue we've had open for this one: https://github.com/JuiceMind/JuiceMind/issues/25

Knowing that we have another request for this, we will likely complete it sooner!

Thanks so much for submitting the request.

**Comment by ProfGoldstein** [comment]
@juicemind-dev  +1
Our school would find this very useful.

**Comment by mjdargen** [comment]
Being able to more easily copy teams, modules, or individual assignments across teams would be incredibly useful.

**Comment by juicemind-dev** [comment]
Hi @ProfGoldstein , @mjdargen , @ianj0710 ,

Could you take a look at the "share items" button that we've implemented on the website? Technically we have completed this issue but I want to make sure it's what you all were looking for.

The "Share items" button is below the "Create item" button on the left sidebar below all of the projects and folders you've made.

**Comment by mjdargen** [comment]
When I click the "Share items" button, it redirects to the "Project share links" page. When I click on the "New Link" button, it redirects to a blank page that never loads. This happens in both Firefox and Chrome.

**Comment by juicemind-dev** [comment]
Hmm that's strange sorry about that. Let me check why that's happening.

**Comment by ProfGoldstein** [comment]
OK, I'll wait to hear from you about this before trying it.
--Ira


Dr. Ira Goldstein (he/him)
Associate Professor of Computer Science
Siena College
515 Loudon Rd.
Loudonville, NY 12211
518.782.6613

*Siena College is a learning community advancing the ideals of a liberal
arts education, rooted in its identity as a Franciscan and Catholic
institution.*

*CONFIDENTIALITY NOTICE: This e-mail, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited. If you received this e-mail and are not the
intended recipient, please inform the sender by e-mail reply and
destroy all copies of the original message.*

**Comment by juicemind-dev** [comment]
Hi all, it should be working now - can you try?

**Comment by mjdargen** [comment]
It seems to work for the most part now. However, the "edit" button does not work after you create the link. It redirects to another blank page.

**Comment by juicemind-dev** [comment]
Hi @mjdargen the edit button should work as well now. Sorry about that. Can you let me know if it all looks good now?

**Comment by mjdargen** [comment]
It does seem to be working better this morning. However, functionality-wise, I believe it would make more sense that selecting a module/folder would automatically select all items inside that module/folder as opposed to forcing you to manually click each individual checkbox.

**Comment by ProfGoldstein** [comment]
OK, I'm going to plead "Monday Morning".

The following was done in Chrome:
I went into the team that has the items.  I clicked on Share Items, New
Link, Select all, and Create link.  I copied the URL and pasted it into a
new tab.  I selected the destination team (which does not have any projects
in it) and click on Select all and Import Projects and then confirm

All three project names now show up in the destination team.  However, none
of the files were imported and each one has a button that says Initialize
JuiceMind IDE:
[image: image.png]

Clicking on that button brings me to the Create new project screen.

Thoughts?
--Ira


Dr. Ira Goldstein (he/him)
Associate Professor of Computer Science
Siena College
515 Loudon Rd.
Loudonville, NY 12211
518.782.6613

*Siena College is a learning community advancing the ideals of a liberal
arts education, rooted in its identity as a Franciscan and Catholic
institution.*

*CONFIDENTIALITY NOTICE: This e-mail, including any attachments, is for the
sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited. If you received this e-mail and are not the
intended recipient, please inform the sender by e-mail reply and
destroy all copies of the original message.*

**Comment by ProfGoldstein** [comment]
The files are there.  It looks good to me.
Thanks.
