### ISSUE TITLE
Can enter negative numbers in quiz timer, causes quiz to end instantaneously for students

### ISSUE THREAD

**Issue by JosephRyan04** [JuiceMind/JuiceMind#154]
When creating a new quiz as a teacher, one can go move back to the beginning of the input and enter a negative (-) sign. This input does not appear to be back-end validated, allowing the quiz to be saved. Starting this quiz will cause it to instantly end.
![image](https://github.com/JuiceMind/JuiceMind/assets/56212348/df2dc260-616d-4726-b94c-817527063775)
![image](https://github.com/JuiceMind/JuiceMind/assets/56212348/01c608b6-7042-4701-b4a1-a7b71dc3700b)

A quick fix for the front end validation can be implemented as such 
`<input maxlength="4" oninput="this.value = this.value.replace(/[^0-9.]/g, '')"></input>`

Additionally, a slightly more sophisticated validation method with minute and second inputs can be found here. https://codepen.io/JosephRyan04/pen/rNgWbGO

**Comment by juicemind-dev** [comment]
Thanks so much @JosephRyan04 for not only submitting this request but actually giving us the solution! We will update this issue soon once we have this updated.
