### ISSUE TITLE
Navigating through a CS Awesome project is really slow and laggy

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#159]

**Comment by juicemind-dev** [comment]
What about it exactly do you think you were referring to?

**Comment by mark-juicemind** [comment]
https://github.com/JuiceMind/JuiceMind/assets/170837121/7a5b1a2d-b1b7-40c7-91c9-53fe184b81eb


I noticed I get lag when I switch from one component to another.

**Comment by mark-juicemind** [comment]
Also notice the difference in speed when switching tabs between a big project like CS awesome and a smaller custom project.



https://github.com/JuiceMind/JuiceMind/assets/170837121/03e5ccf1-d5b3-424d-8abf-e128315b445d

**Comment by mark-juicemind** [comment]
I also get it when trying to make new components:



https://github.com/JuiceMind/JuiceMind/assets/170837121/39d8a3fa-3c75-48a1-9d5b-5b58f569a63e
