### ISSUE TITLE
Remove the upload .zip button if you've already done it

### ISSUE THREAD

**Issue by maegan** [JuiceMind/JuiceMind#167]
I've already uploaded my .zip file from replit and I still have the button that says "upload .zip file", even if I collapse the tools menu

**Comment by juicemind-dev** [comment]
Hi Mary Anne,

Yes, we should definitely remove it once you've uploaded.

We have a similar issue open: #32 

Since you've requested this feature then we will push it to the top of our roadmap. Thanks so much for submitting this!
