### ISSUE TITLE
Allow 'input' for Python

### ISSUE THREAD

**Issue by missrthomas** [JuiceMind/JuiceMind#171]
There's no "input" option for Python which significantly limits what we can teach, as most of the core GCSE curriculum expects/relies on using inputs. I also think this can confuse pupils as they may not understand the point of using variables - one of my best explanations for this is "because you're the programmer and you don't know what the user will input when they run the code". It would be great if we were able to teach inputs.

**Comment by juicemind-dev** [comment]
Hi @missrthomas !

The inputs should be working for Python, are you using the Teams platform?

**Comment by juicemind-dev** [comment]
Ok got it. I am closing the issue since it should be working in Teams.
