### ISSUE TITLE
problem with not overwriting the default main.py when uploading zip file

### ISSUE THREAD

**Issue by robinflatland** [JuiceMind/JuiceMind#172]
In coding assignments, when I upload a zip file containing a main.py (among other files), it doesn't overwrite the default main.py that comes with the coding assignment, even though I pressed the button asking it to override the project files.  The other files in the zip all get uploaded into the coding assignment, just not the main.py.  I am using Teams and the project type that I am using for the coding assignment is Python with Pillow.  Thank you for your help with this!

**Comment by juicemind-dev** [comment]
Hi @robinflatland !

Thanks for creating this issue. Our team is looking into it right now and should have a solution soon (hopefully within the next couple of hours). I will comment here once it is updated.

**Comment by juicemind-dev** [comment]
@robinflatland we have just pushed an update which should fix this issue. Can you take a look and make sure that things are working as expected before I close this issue?

Thanks so much!

**Comment by robinflatland** [comment]
Thank you - that fixed the problem!

**Comment by juicemind-dev** [comment]
Great!

Thanks again @robinflatland  for posting this issue. If you run into any other problems please create a new issue and we will handle it right away!
