### ISSUE TITLE
Download Project doesn't download all of the project files

### ISSUE THREAD

**Issue by robinflatland** [JuiceMind/JuiceMind#175]
I've got a Juicemind project that contains 5 files.  But when I select Download Project, it creates a zip file that contains only 3 of the 5 files.  I took two screenshots, one showing the 5 project files being downloaded and one showing what 3 files are in the zip file that is created.

[Picture of 5 files being downloaded](https://drive.google.com/file/d/111vE6_NQJML8goEe1zJ2c72J9ej5NgOw/view?usp=sharing)

[Picture showing the 3 files in the zip file](https://drive.google.com/file/d/1Nb5kQR6OgmgVFPfW8JPK_bJr1d1h0t3u/view?usp=sharing)

If you want to jump into my project  to look at it, it is in my team DevelopmentCSIS110 and the project is Lab 1 - First Things First.  

Thank you! Robin

**Comment by juicemind-dev** [comment]
Hi @robinflatland !

Thanks for reporting this issue. We're looking into it right now. We will likely have this solved in the next couple of hours and report back here once it's complete.

**Comment by juicemind-dev** [comment]
Hi @robinflatland can you check to see if the download is working as expected now? We have just pushed out an update which should solve the problem. Remember to refresh the screen 2 times before trying to make sure that the update propagates.

Thanks!

**Comment by robinflatland** [comment]
Yes, it is working as expected now!  Thank you for the quick fix!

Robin

**Comment by juicemind-dev** [comment]
Ok great to hear! We are closing the issue now then.
