### ISSUE TITLE
Code Text not in black/white

### ISSUE THREAD

**Issue by MrDiazSFHS** [JuiceMind/JuiceMind#178]
When selecting a keyword, allow the text to change font as is now, but not highlighting... too distracting.

Thanks

**Comment by juicemind-dev** [comment]
Hi @MrDiazSFHS could you possibly show an image of what you mean exactly? We are having a little bit of trouble trying to determine exactly what you're looking for.

Thanks!

**Comment by MrDiazSFHS** [comment]
Currently when using the Code tool when highlighting a word it shows in black background and white text. A bit districting. I found a workaround to just change the font instead. 

I am glad that I was able to import my Replit Teams into JuiceMind... Great job!
![Screenshot 2024-06-19 092629](https://github.com/JuiceMind/JuiceMind/assets/68512751/a165409c-614d-4d9f-8ce7-c8acd761740d)

**Comment by juicemind-dev** [comment]
Ok got it. We will take this into note for the future. We're glad you were able to import your Replit Teams! We will be making an announcement very soon regarding the official release of our Coding Rooms import tool so that you can import your Coding Rooms courses into JuiceMind.
