### ISSUE TITLE
Console on Right Panel

### ISSUE THREAD

**Issue by MrDiazSFHS** [JuiceMind/JuiceMind#179]
Allow the Console Panel to be on the right hand side panel.  Huge help when coding longer assignments.

Thanks
David Diaz

**Comment by juicemind-dev** [comment]
Hi @MrDiazSFHS, thanks for reporting this!

You can actually add the console panel to the right by clicking on the 3 dots at the top right of the ide and add a panel to the right. The resulting setup will look like so:

<img width="473" alt="image" src="https://github.com/JuiceMind/JuiceMind/assets/170696439/54d4503a-72ff-4b71-8eeb-d7b9709383d5">

Let me know if you need any more specific assistance on this or if you prefer a different solution.
