### ISSUE TITLE
Students able to read Instructions.md file as markup file

### ISSUE THREAD

**Issue by MrDiazSFHS** [JuiceMind/JuiceMind#180]
Allow students to read Instructions or Instruction.md markup file on the right panel. As they go into full screen on the coding Screen they can continue to read instructions.

Thanks
David Diaz

**Comment by juicemind-dev** [comment]
It should be possible to view on the right panel if you create a new panel. Also, we advise that you sync your instruction.md so that it populates the left panel. This way students wouldn't need to have the right panel added.

What are your thoughts on the comments above @MrDiazSFHS ?
