### ISSUE TITLE
Unable to delete backspace and bullet point acts weird in multiple choice

### ISSUE THREAD

**Issue by juicemind-dev** [JuiceMind/JuiceMind#183]
when you type "- " it automatically sends you to the new line and then if you try deleting the bullet point as a whole it doesn't work.

The expected behavior is for the bullet point to delete after you press backspace and it should just leave "- "

**Comment by guido-ferraro** [comment]
@juicemind-dev 

This isn't the BulletList extension not working, but the expected behavior: https://tiptap.dev/docs/editor/extensions/nodes/bullet-list

Do we want to re-consider overwriting it with a custom solution (no off-the-shelf solution available for this in the extension's API)?

**Comment by guido-ferraro** [comment]
Moving this to `Done` based on daily call discussion.
