### ISSUE TITLE
option to download an individual file 

### ISSUE THREAD

**Issue by robinflatland** [JuiceMind/JuiceMind#186]
Hi,

For our course curriculum we need students to be able to download individual files contained in their project.  For example in Replit, when you pressed the dots to the right of any file name in the project's file listing, one of the options is to download the file.  Could this be added to Juicemind?  

(I know that it is possible to download the entire project as a zip file, but what we need for the lab experiences is the ability for beginner students to easily download a particular file (which is often an image that they created), without having the overhead of them dealing with zipped files.)

Thank you, Robin

**Comment by juicemind-dev** [comment]
Hi @robinflatland . Yes, this is definitely possible and is part of our roadmap. You can see there is another ticket open for this feature: #166 , and the expected release date is June 27. Will that release date work for you?

Thanks so much!

**Comment by robinflatland** [comment]
Yes, that is excellent.   I didn't realize MaryAnne had put in the same
request!  Thank you,

Robin

**Comment by juicemind-dev** [comment]
Perfect, no problem! We will update you once the feature is released!

**Comment by robinflatland** [comment]
Hello,

I am checking on the status of this download an individual file ticket item
originally expected to be released June 27.  I don't see the download
option yet.  Will it be available soon?  I'm updating my fall curriculum
now which needs the option.  Thank you!

Robin

**Comment by robinflatland** [comment]
Hello,

I'm checking in on the single file download feature to see if you have a
new expected release date.  Also, I tried the Download Project option
(screenshot below) and it doesn't seem to do anything.  There is no
response when it is selected and as far as I can tell no download occurs.

Thank you for your help with these things as we prepare for starting the
fall semester!
Robin

[image: image.png]

**Comment by juicemind-dev** [comment]
Hi @robinflatland we'll try to get this one completed today for you. Sorry for the delay. We will check on the download project as well.

**Comment by robinflatland** [comment]
Thank you! That works great!

Robin
