### ISSUE TITLE
import coding rooms

### ISSUE THREAD

**Issue by gloomis69** [JuiceMind/JuiceMind#206]
I tried importing a couple of courses. It seems to work for the unzipping and analyzing, but breaks in the converting to Juicemind
[cr-course-web-design.zip](https://github.com/user-attachments/files/16052967/cr-course-web-design.zip)
[cr-course-advanced-computing-concepts.zip](https://github.com/user-attachments/files/16052970/cr-course-advanced-computing-concepts.zip)

**Comment by juicemind-dev** [comment]
Ok thanks so much. We are doing a sort of soft release today because there will likely be some issues with some users' imports. We are checking your uploads now and will get back to you shortly.
