### ISSUE TITLE
Tests do not show students input for test (only shows output discrepancy)

### ISSUE THREAD

**Issue by brkeating42** [JuiceMind/JuiceMind#208]
The old site allowed students to view the outcome of the input/output tests in 2 views. One view showed just the output differences and the other view showed what input was given to the test. In the new site, the students can only see the differences in output but don't have a way to see what input the test was testing on. Please add this functionality back in.

**Comment by juicemind-dev** [comment]
Hi @brkeating42 , we have just pushed an update to our platform to now show the input when running the tests. Here is a screenshot of how that looks:

<img width="668" alt="image" src="https://github.com/user-attachments/assets/93d64038-2992-4ad3-a9e0-69380abccb09">

Let me know if this is what you're looking for
