### ISSUE TITLE
New Lesson Won't Appear in Teams

### ISSUE THREAD

**Issue by gloomis69** [JuiceMind/JuiceMind#216]
This was fine yesterday. Today, when I make a new lesson in a team, the lesson page is generated, but won't load. When I refresh the page, it flashes on screen for a quick moment then the entire page goes blank.  Older existing lessons load fine. New coding assignments also work fine. Very strange issue.

**Comment by gloomis69** [comment]
Console log for this issue:

in prod
index-8e64fc49.js:19872 in production
index-8e64fc49.js:6066 db vh$1 {_authCredentials: z$7, _appCheckCredentials: Y$5, _databaseId: gI, _app: FirebaseAppImpl, type: 'firestore', …}
index-8e64fc49.js:6066 products in proutes undefined
index-8e64fc49.js:6066 undefined
index-8e64fc49.js:6066 Initial render
index-8e64fc49.js:6066 unable to find website in query string
index-8e64fc49.js:6066 pulling getProducts
index-8e64fc49.js:6066 payments StripePayments {app: FirebaseAppImpl, options: {…}, components: {…}}
index-8e64fc49.js:6066 products in proutes undefined
index-8e64fc49.js:6066 Initial render
index-8e64fc49.js:6066 db vh$1 {_authCredentials: z$7, _appCheckCredentials: Y$5, _databaseId: gI, _app: FirebaseAppImpl, type: 'firestore', …}
2index-8e64fc49.js:6066 products in proutes undefined
index-8e64fc49.js:6066 POSTING THE MESSAGE
index-8e64fc49.js:6066 products in proutes undefined
index-8e64fc49.js:6066 weird user data {myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, totalAssignedQuizGamesStarted: 0, teacherPin: 917213, …}
index-8e64fc49.js:6066 db vh$1 {_authCredentials: z$7, _appCheckCredentials: Y$5, _databaseId: gI, _app: FirebaseAppImpl, type: 'firestore', …}
index-8e64fc49.js:6066 products in proutes undefined
index-8e64fc49.js:6066 db vh$1 {_authCredentials: z$7, _appCheckCredentials: Y$5, _databaseId: gI, _app: FirebaseAppImpl, type: 'firestore', …}
index-8e64fc49.js:6066 products in proutes undefined
index-8e64fc49.js:6066 finished pulling getProducts
index-8e64fc49.js:6066 stripeproductsinpcontext (72) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 (2) [{…}, {…}]
index-8e64fc49.js:6066 monthly price {active: true, description: null, interval: 'month', metadata: {…}, tax_behavior: 'unspecified', …}
index-8e64fc49.js:6066 (2) [{…}, {…}]
index-8e64fc49.js:6066 monthly price {transform_quantity: null, tiers: null, metadata: {…}, currency: 'usd', active: true, …}
index-8e64fc49.js:6066 (2) [{…}, {…}]
index-8e64fc49.js:6066 monthly price {tax_behavior: 'unspecified', product: 'prod_OQiFeKv7zRcB6F', metadata: {…}, transform_quantity: null, currency: 'usd', …}
index-8e64fc49.js:6066 (2) [{…}, {…}]
index-8e64fc49.js:6066 monthly price {type: 'recurring', trial_period_days: 30, tiers_mode: null, unit_amount: 2499, recurring: {…}, …}
index-8e64fc49.js:6066 updatedProducts (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 products in proutes (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 userData in subscriptions (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 teamProjects []
index-8e64fc49.js:6066 HI WE'RE HERE teams/5YImiImjHKqFg2tOaB9F
index-8e64fc49.js:6066 fileSystem undefined
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 undefined 'teamViewUser1234'
index-8e64fc49.js:6066 fileSystem in course home undefined
index-8e64fc49.js:6066 we're trying the snapshot
index-8e64fc49.js:6066 file system is different!
index-8e64fc49.js:6066 teamProjects []
index-8e64fc49.js:6066 HI WE'RE HERE teams/5YImiImjHKqFg2tOaB9F
index-8e64fc49.js:6066 fileSystem undefined
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 undefined 'teamViewUser1234'
index-8e64fc49.js:6066 fileSystem in course home undefined
index-8e64fc49.js:6066 data11111111111 {myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, totalAssignedQuizGamesStarted: 0, teacherPin: 917213, …}
index-8e64fc49.js:6066 products in proutes (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 userData in subscriptions (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 teamProjects []
index-8e64fc49.js:6066 HI WE'RE HERE teams/5YImiImjHKqFg2tOaB9F
index-8e64fc49.js:6066 fileSystem undefined
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 undefined 'teamViewUser1234'
index-8e64fc49.js:6066 targetItem234 null
index-8e64fc49.js:6066 fileSystem in course home undefined
index-8e64fc49.js:6066 [] 'selectedIds'
index-8e64fc49.js:6066 fileSystem undefined
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 undefined 'teamViewUser1234'
index-8e64fc49.js:6066 No matching documents.
index-8e64fc49.js:6066 teamProjects []
index-8e64fc49.js:6066 HI WE'RE HERE teams/5YImiImjHKqFg2tOaB9F
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 fileSystem undefined
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 undefined 'teamViewUser1234'
index-8e64fc49.js:6066 targetItem234 null
index-8e64fc49.js:6066 fileSystem in course home undefined
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 teamData.teamMembers {CehfT6gCaOTzZXF55T7bXzkx11H3: {…}, Xq06VuHSk9Mvu04dpi0PoUWX6HD3: {…}}
index-8e64fc49.js:6066 teamProjects []
index-8e64fc49.js:6066 HI WE'RE HERE teams/5YImiImjHKqFg2tOaB9F
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 fileSystem (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 {id: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', name: 'Gregory Loomis', email: 'gregory.loomis@fcps.org', isAdmin: true} 'teamViewUser1234'
index-8e64fc49.js:6066 targetItem234 null
index-8e64fc49.js:6066 file system is different!
index-8e64fc49.js:6066 teamProjects []
index-8e64fc49.js:6066 HI WE'RE HERE teams/5YImiImjHKqFg2tOaB9F
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 initializing points
index-8e64fc49.js:6066 codingAssignmentDetails {points: 0, projectId: 'e2b4f551-a454-4343-8054-40e375476839'}
index-8e64fc49.js:6066 contentItem {type: 'heading', attrs: {…}, content: Array(1)}
index-8e64fc49.js:6066 contentItem {type: 'paragraph', attrs: {…}, content: Array(1)}
index-8e64fc49.js:6066 contentItem {type: 'shortAnswer', attrs: {…}}
index-8e64fc49.js:6066 contentItem {type: 'paragraph', attrs: {…}, content: Array(2)}
index-8e64fc49.js:6066 contentItem {type: 'shortAnswer', attrs: {…}}
index-8e64fc49.js:6066 contentItem {type: 'paragraph', attrs: {…}, content: Array(2)}
index-8e64fc49.js:6066 contentItem {type: 'shortAnswer', attrs: {…}}
index-8e64fc49.js:6066 contentItem {type: 'paragraph', attrs: {…}, content: Array(2)}
index-8e64fc49.js:6066 contentItem {type: 'paragraph', attrs: {…}, content: Array(1)}
index-8e64fc49.js:6066 contentItem {type: 'shortAnswer', attrs: {…}}
index-8e64fc49.js:6066 contentItem {type: 'paragraph', attrs: {…}}
index-8e64fc49.js:6066 contentItem {type: 'shortAnswer', attrs: {…}}
index-8e64fc49.js:6066 contentItem {type: 'paragraph', attrs: {…}}
index-8e64fc49.js:6066 points about to dispatch (5) [{…}, {…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 getObjectFromAmbiguousType(itemData.content) {type: 'doc', content: Array(13)}
index-8e64fc49.js:6066 fileSystem (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 {id: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', name: 'Gregory Loomis', email: 'gregory.loomis@fcps.org', isAdmin: true} 'teamViewUser1234'
index-8e64fc49.js:6066 targetItem234 null
index-8e64fc49.js:6066 course content page
index-8e64fc49.js:6066 fileSystem11112 (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 initialContent {type: 'doc', content: Array(13)}
index-8e64fc49.js:6066 hasImportIssues false
index-8e64fc49.js:6066 error undefined
5index-8e64fc49.js:6066 usersProgress undefined
index-8e64fc49.js:6066 {id: '785df0fb-28e1-4df9-8866-f591def5630a', name: 'Intro to CSS', type: 'lesson'} 'itemmm2222'
index-8e64fc49.js:6066 products in proutes (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 userData in subscriptions (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 teamProjects []
index-8e64fc49.js:6066 HI WE'RE HERE teams/5YImiImjHKqFg2tOaB9F
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 teamData {fileSystem: '[{"id":"8073a9cb-31d1-422d-8a1d-47d740ffb126","nam…me":"CSS Box Method","type":"coding-assignment"}]', userId: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', isCourseInitiatedV2: true, teamMembers: {…}, name: 'ACC for FCPS teachers', …}
index-8e64fc49.js:6066 fileSystem (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 {id: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', name: 'Gregory Loomis', email: 'gregory.loomis@fcps.org', isAdmin: true} 'teamViewUser1234'
index-8e64fc49.js:6066 targetItem234 null
index-8e64fc49.js:6066 course content page
index-8e64fc49.js:6066 fileSystem11112 (4) [{…}, {…}, {…}, {…}]
5index-8e64fc49.js:6066 usersProgress undefined
index-8e64fc49.js:6066 unable to find website in query string
index-8e64fc49.js:6066 products in proutes (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 userData in subscriptions (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 fileSystem (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 {id: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', name: 'Gregory Loomis', email: 'gregory.loomis@fcps.org', isAdmin: true} 'teamViewUser1234'
index-8e64fc49.js:6066 targetItem234 null
index-8e64fc49.js:6066 initializing points
index-8e64fc49.js:6066 codingAssignmentDetails {points: 0, projectId: '785df0fb-28e1-4df9-8866-f591def5630a'}
index-8e64fc49.js:6066 points about to dispatch []
index-8e64fc49.js:6066 getObjectFromAmbiguousType(itemData.content) null
index-8e64fc49.js:6066 fileSystem (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 {subscriptions: Array(0), cancelSubscriptionAtEndOfPeriod: false, myStudents: {…}, totalCustomQuizGamesStarted: 0, hasCreatedATeamProject: true, …} 'userData1234'
index-8e64fc49.js:6066 {id: 'Xq06VuHSk9Mvu04dpi0PoUWX6HD3', name: 'Gregory Loomis', email: 'gregory.loomis@fcps.org', isAdmin: true} 'teamViewUser1234'
index-8e64fc49.js:6066 targetItem234 null
index-8e64fc49.js:6066 course content page
index-8e64fc49.js:6066 fileSystem11112 (4) [{…}, {…}, {…}, {…}]
index-8e64fc49.js:6066 initialContent null
index-8e64fc49.js:6066 TypeError: Cannot read properties of null (reading 'content')
    at index-8e64fc49.js:16752:63512
    at Qj (index-8e64fc49.js:40:27039)
    at Hk (index-8e64fc49.js:40:47342)
    at Ek (index-8e64fc49.js:40:40838)
    at jg (index-8e64fc49.js:38:3706)
    at Wk (index-8e64fc49.js:40:46089)
    at Pk (index-8e64fc49.js:40:44951)
    at Gk (index-8e64fc49.js:40:39838)
    at $p (index-8e64fc49.js:25:1729)
    at Ip (index-8e64fc49.js:25:2141)
    at n (assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116:119)
    at p (assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117:82)
(anonymous) @ index-8e64fc49.js:6066
Li$2 @ index-8e64fc49.js:40
Qi$2.ip.componentDidCatch.tp.callback @ index-8e64fc49.js:40
sh$1 @ index-8e64fc49.js:38
kk @ index-8e64fc49.js:40
ik @ index-8e64fc49.js:40
hk @ index-8e64fc49.js:40
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Gk @ index-8e64fc49.js:40
$p @ index-8e64fc49.js:25
Ip @ index-8e64fc49.js:25
n @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116
p @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
postMessage (async)
y @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
J.setImmediate @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:119
Mp @ index-8e64fc49.js:25
Pp @ index-8e64fc49.js:25
bt.unstable_scheduleCallback @ index-8e64fc49.js:25
Fk @ index-8e64fc49.js:40
Dk @ index-8e64fc49.js:40
gi$2 @ index-8e64fc49.js:40
ii$2 @ index-8e64fc49.js:38
om @ index-8e64fc49.js:16752
await in om (async)
(anonymous) @ index-8e64fc49.js:16752
Qj @ index-8e64fc49.js:40
Hk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Gk @ index-8e64fc49.js:40
$p @ index-8e64fc49.js:25
Ip @ index-8e64fc49.js:25
n @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116
p @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
postMessage (async)
y @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
J.setImmediate @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:119
Mp @ index-8e64fc49.js:25
Pp @ index-8e64fc49.js:25
bt.unstable_scheduleCallback @ index-8e64fc49.js:25
Fk @ index-8e64fc49.js:40
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
(anonymous) @ index-8e64fc49.js:40
index-8e64fc49.js:6066 TypeError: Cannot read properties of null (reading 'content')
    at index-8e64fc49.js:16752:63512
    at Qj (index-8e64fc49.js:40:27039)
    at Hk (index-8e64fc49.js:40:47342)
    at Ek (index-8e64fc49.js:40:40838)
    at jg (index-8e64fc49.js:38:3706)
    at Wk (index-8e64fc49.js:40:46089)
    at Pk (index-8e64fc49.js:40:44951)
    at Gk (index-8e64fc49.js:40:39838)
    at $p (index-8e64fc49.js:25:1729)
    at Ip (index-8e64fc49.js:25:2141)
    at n (assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116:119)
    at p (assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117:82)
(anonymous) @ index-8e64fc49.js:6066
Li$2 @ index-8e64fc49.js:40
Ni$2.tp.callback @ index-8e64fc49.js:40
sh$1 @ index-8e64fc49.js:38
kk @ index-8e64fc49.js:40
ik @ index-8e64fc49.js:40
hk @ index-8e64fc49.js:40
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Gk @ index-8e64fc49.js:40
$p @ index-8e64fc49.js:25
Ip @ index-8e64fc49.js:25
n @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116
p @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
postMessage (async)
y @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
J.setImmediate @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:119
Mp @ index-8e64fc49.js:25
Pp @ index-8e64fc49.js:25
bt.unstable_scheduleCallback @ index-8e64fc49.js:25
Fk @ index-8e64fc49.js:40
Dk @ index-8e64fc49.js:40
gi$2 @ index-8e64fc49.js:40
ii$2 @ index-8e64fc49.js:38
om @ index-8e64fc49.js:16752
await in om (async)
(anonymous) @ index-8e64fc49.js:16752
Qj @ index-8e64fc49.js:40
Hk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Gk @ index-8e64fc49.js:40
$p @ index-8e64fc49.js:25
Ip @ index-8e64fc49.js:25
n @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116
p @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
postMessage (async)
y @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
J.setImmediate @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:119
Mp @ index-8e64fc49.js:25
Pp @ index-8e64fc49.js:25
bt.unstable_scheduleCallback @ index-8e64fc49.js:25
Fk @ index-8e64fc49.js:40
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
(anonymous) @ index-8e64fc49.js:40
index-8e64fc49.js:16752 Uncaught TypeError: Cannot read properties of null (reading 'content')
    at index-8e64fc49.js:16752:63512
    at Qj (index-8e64fc49.js:40:27039)
    at Hk (index-8e64fc49.js:40:47342)
    at Ek (index-8e64fc49.js:40:40838)
    at jg (index-8e64fc49.js:38:3706)
    at Wk (index-8e64fc49.js:40:46089)
    at Pk (index-8e64fc49.js:40:44951)
    at Gk (index-8e64fc49.js:40:39838)
    at $p (index-8e64fc49.js:25:1729)
    at Ip (index-8e64fc49.js:25:2141)
    at n (assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116:119)
    at p (assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117:82)
(anonymous) @ index-8e64fc49.js:16752
Qj @ index-8e64fc49.js:40
Hk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Gk @ index-8e64fc49.js:40
$p @ index-8e64fc49.js:25
Ip @ index-8e64fc49.js:25
n @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116
p @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
postMessage (async)
y @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
J.setImmediate @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:119
Mp @ index-8e64fc49.js:25
Pp @ index-8e64fc49.js:25
bt.unstable_scheduleCallback @ index-8e64fc49.js:25
Fk @ index-8e64fc49.js:40
Dk @ index-8e64fc49.js:40
gi$2 @ index-8e64fc49.js:40
ii$2 @ index-8e64fc49.js:38
om @ index-8e64fc49.js:16752
await in om (async)
(anonymous) @ index-8e64fc49.js:16752
Qj @ index-8e64fc49.js:40
Hk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Gk @ index-8e64fc49.js:40
$p @ index-8e64fc49.js:25
Ip @ index-8e64fc49.js:25
n @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:116
p @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
postMessage (async)
y @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:117
J.setImmediate @ assets%2Fskulpt%2Fskulpt.min.js?alt=media&token=79e4d940-c505-4d0e-a59c-478fe4bd80ff:119
Mp @ index-8e64fc49.js:25
Pp @ index-8e64fc49.js:25
bt.unstable_scheduleCallback @ index-8e64fc49.js:25
Fk @ index-8e64fc49.js:40
Wk @ index-8e64fc49.js:40
Pk @ index-8e64fc49.js:40
Ek @ index-8e64fc49.js:40
jg @ index-8e64fc49.js:38
(anonymous) @ index-8e64fc49.js:40

**Comment by juicemind-dev** [comment]
Hi @gloomis69 can you take a look now and see if it has been resolved with our newest updates?
