### ISSUE TITLE
MCQ and Parsons lag a lot when clicking inside the prompt (cursor takes 2-3 seconds to appear)

### ISSUE THREAD

**Issue by juicemind-dev** [JuiceMind/JuiceMind#228]

**Comment by guido-ferraro** [comment]
Note: This was noted to occur on accounts with lots of teams, lessons and content, performance issue is likely related to querying data and running code irrelevant to current view.

**Comment by guido-ferraro** [comment]
`@mui/material` library builds the html for `Menu` component even when prop `open` is set to `false`. Rendering needs to be prevented by conditionally rendering the component so performance doesn't suffer for teams with large file systems. Take into account when controlling other `@mui/material` components using similar props.

Code reference: https://github.com/JuiceMind/juicemind-web-app/blob/f1e0160ebb48a94dd45a36c832f3a001b9fe3328/src/components/coding-rooms/sidebar-coding-rooms/SidebarItem.jsx#L198
