### ISSUE TITLE
Empty split view on student's side

### ISSUE THREAD

**Issue by guido-ferraro** [JuiceMind/JuiceMind#261]
Reproduction (video attached):
1. Open Settings
2. Open Lesson
3. Open Settings

https://github.com/user-attachments/assets/16b13035-e706-48c9-85df-3650e1d1f2b5

**Comment by juicemind-dev** [comment]
I think I might have already fixed this on my own time in origin/kahoot-phil. Can we double check that this is the case?

**Comment by guido-ferraro** [comment]
@juicemind-dev I think this was fixed in [PR 158](https://github.com/JuiceMind/juicemind-web-app/pull/158):

https://github.com/user-attachments/assets/3c5e557f-bf5f-442c-9483-165d2e44b55a

An additional, probably unexpected behavior noticed to consider creating an issue for, is the fact that the student can open a `Lesson` tab when there's no file for it resulting in a blank screen. I propose rendering the button only if the file exist unless, we would want a `lesson.md` file to be mandatory. I wouldn't consider this high priority, though.
