### ISSUE TITLE
images not displaying within viewing pane 

### ISSUE THREAD

**Issue by jlinseman** [JuiceMind/JuiceMind#276]
instructions.md file has linked to an asset (image.png) but will not display in the live display pane.
![image](https://github.com/user-attachments/assets/2dbe643c-fd2d-48d1-a037-75c1919f6c4c)

**Comment by juicemind-dev** [comment]
Hi @jlinseman  thanks for adding this issue. We will let you know soon once it's solved

**Comment by juicemind-dev** [comment]
Hi @jlinseman we've just pushed out an update which we hope will fix this issue. Can you check and let us know? Thanks so much!
