### ISSUE TITLE
Can't reorder modules

### ISSUE THREAD

**Issue by mjdargen** [JuiceMind/JuiceMind#282]
While using the replit import tool, it imported my modules and assignments out of order. Assignments can be rearranged easily by clicking and dragging. However, modules can't be reordered. Whenever you try to click and drag a module, it automatically nests it inside another module. If you try to drag it outside the module, it only places it at the very bottom. It does not reorder it at all. There needs to be an option for reordering modules.

https://github.com/user-attachments/assets/df5854a3-1cfd-4f30-922d-f6a37b66025d

**Comment by juicemind-dev** [comment]
It also doesn't let you move a module inside another module into the first spot. You have to place it into the second spot and then drag it up into the first spot once your module is already inside the other module.
