### ISSUE TITLE
Can't delete Teams

### ISSUE THREAD

**Issue by mjdargen** [JuiceMind/JuiceMind#283]
When you click on "Delete Team", it does not delete the team. It only moves it to the Archived Teams section.

**Comment by juicemind-dev** [comment]
Hi @mjdargen , yes we will add the Archive Team vs Delete Team button. Thanks for mentioning this.

**Comment by mjdargen** [comment]
Both buttons exist. However, the Delete Team button seems to do the exact same thing as the Archive Team button.
