### ISSUE TITLE
add pydraw graphics package

### ISSUE THREAD

**Issue by blindler** [JuiceMind/JuiceMind#306]
pre install pydraw for use with python.  full documentation of the graphics package is posted at pydraw.graphics
This package was developed and is maintained by one of my former students, so it is customized to our specific needs.

**Comment by juicemind-dev** [comment]
Thanks so much @blindler . We are on it and will try get that out for you some time later today.

**Comment by juicemind-dev** [comment]
Hi @blindler we've added pydraw to the Python with Turtle package. Can you let me know if it's working? We can add it to other templates if you prefer to not use the Python with Turtle one.

**Comment by blindler** [comment]
> Hi @blindler we've added pydraw to the Python with Turtle package. Can you let me know if it's working? We can add it to other templates if you prefer to not use the Python with Turtle one.

Yessir, that works great!  and with Turtle package is fine - kind of makes sense to match it with another graphics package - could it be added to the Tkinter as well?  We normally choose Python with Turtle the pydraw utilizes Tkinter so it might also be a good match.

**Comment by juicemind-dev** [comment]
Ok awesome! We've just added it to the Tkinter one as well. We will close this issue now, you can reopen if you'd like anything else updated here.

Thanks so much!

**Comment by blindler** [comment]
Thank you!

*Barry Lindler,* NBCT Mathematics
AP Computer Science/Computer Programming/APCS Principles
STEM / AGP Coordinator
CTE Department Chair
Boys and Girls Head Cross Country Coach
Dutch Fork High School
803-476-3479, email is best contact.
