### ISSUE TITLE
Unable to display webview for an html site

### ISSUE THREAD

**Issue by lisawaddellatnorth** [JuiceMind/JuiceMind#315]
My webview just shows a broken page:
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/50313475-7224-4e43-8bd6-0d00530121b4">

 when I try to go directly to the linkin the error message, this is what I see:

<img width="769" alt="image" src="https://github.com/user-attachments/assets/5cf71fce-5222-4c52-9df1-4f57a2ac35c3">

**Comment by juicemind-dev** [comment]
Yes got it, sorry about this. We're fixing it now.

**Comment by juicemind-dev** [comment]
Hi @lisawaddellatnorth can you make sure that it is fixed? We should have fixed it yesterday.

**Comment by juicemind-dev** [comment]
Awesome! Sorry about the issue yesterday!
