### ISSUE TITLE
group assignment not working in project

### ISSUE THREAD

**Issue by robinflatland** [JuiceMind/JuiceMind#320]
Hi,

I've created a project for a team with 4 members.  When I go to create the groups, there are no unassigned members listed.  How do I assign members to groups?  I've included a screen shot showing the group assignment screen and you can see there are four members listed on the right, but they are not available to put into groups.  The team is DevelopmentCSIS110 in my Juicemind account and the project is Lab 4.

Thank you,
Robin

![Capture](https://github.com/user-attachments/assets/d57308a7-3a58-487f-a3c6-71470122de89)
@profgoldstein
@juicemind-dev

**Comment by teach8** [comment]
I've also had this issue!

**Comment by juicemind-dev** [comment]
Hi @robinflatland and @teach8 , we're investigating this issue right now and will update you shortly on the status.

**Comment by juicemind-dev** [comment]
Hi @robinflatland @teach8 , we've just pushed out an update that should resolve this issue. Let us know if it's working!

**Comment by robinflatland** [comment]
Yes, thank you!  I can see the team members now and I am able to add them
to groups.  Thank you!

Robin

**Comment by teach8** [comment]
Yes, fixed. Thank you!

**Comment by juicemind-dev** [comment]
Great!
