### ISSUE TITLE
Unable to update student grade manually.

### ISSUE THREAD

**Issue by KingLeonidas** [JuiceMind/JuiceMind#341]
I have tried to update student grade manually on each ide but it doesn't update the total in the student grades sheet.

**Comment by juicemind-dev** [comment]
Hi @KingLeonidas we're planning on releasing a big update for grading that should make the process much more similar to Coding Rooms and should get rid of these manual grading issues. I will update on here once we fix this.

**Comment by KingLeonidas** [comment]
Thanks!
