### ISSUE TITLE
Can't add/remove table columns or rows 

### ISSUE THREAD

**Issue by kongcathleen** [JuiceMind/JuiceMind#344]
The buttons to add/remove table columns or rows are missing when I edit my lesson on Google Chrome:
![image](https://github.com/user-attachments/assets/4aac49b8-f2e4-492e-9ac0-791e1f9e00a9)
I switched to Edge and was able to see them, but I prefer using Chrome as my browser.

**Comment by juicemind-dev** [comment]
@kongcathleen if you click inside of the table (on any of the cells) it should bring up a grey border. Once you click this grey border it should show the editing options. See the grey border I am referring to below:
<img width="473" alt="image" src="https://github.com/user-attachments/assets/a84d4853-9882-4048-bea3-e6494b157dc4">


Can you let me know if the grey border is showing up?

**Comment by kongcathleen** [comment]
I clicked inside the table and the grey border did not show up. I refreshed the page and then was able to see it though, so maybe it was a one-off error. Thank you!

**Comment by juicemind-dev** [comment]
Hmm that's pretty weird. Yeah maybe it was just one-off. If you see it again let's reopen this.
