### ISSUE TITLE
students unable to get starter code for coding assignment when assignment is a group project

### ISSUE THREAD

**Issue by robinflatland** [JuiceMind/JuiceMind#366]
Hi,

Just today I've run into the problem where students cannot get the starter code for coding assignments.  I publish the assignment and assign the student to a group.  But when they try to access it by clicking on the Create starter code button, nothing happens.  Here is a video showing this.

https://youtu.be/R0N_k_ZZQGw

This was working fine last week.  I'm running a demo for teachers today at 3pm EST.  Any way it might work by then?    Thank you!
Robin

@juicemind-dev 
@profgoldstein

**Comment by juicemind-dev** [comment]
Hi @robinflatland that's very strange, we're checking now.

**Comment by robinflatland** [comment]
I was playing with it a bit more, and it works fine if the coding assignment does not use groups.  When I use groups, the student cannot access the starter files, even though they are assigned to a group.

@juicemind-dev 
@profgoldstein

**Comment by juicemind-dev** [comment]
Hi @robinflatland it is fixed now, sorry for the outage there.

**Comment by robinflatland** [comment]
Thank you!! I tried it and it is working great for me now.

Robin
