### ISSUE TITLE
No way of knowing if students have submitted answers

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#404]
As the teacher, for assignments, there is no way of knowing if a student has submitted (unless they score above 0, then they will have a score)

For lessons, if the student's answer is correct, then a "correct" will show up below their IDE. However, if the student's answer is incorrect, nothing will be shown.

As for other question types like multiple choice or fill in the blank, submitting does show up properly. 

There is also currently no way of knowing if a student has submitted an answer if no unit tests are used.

**Comment by JL248** [comment]
It would be great to know when a student submitted/resubmitted the assignment even if no unit tests were used. Some kind of mark next to the student's name in the list of students on the right. So, the teacher could know at a glance which students are waiting for their work to be checked (or rechecked in case of resubmissions)

**Comment by mrlo-codes** [comment]
It would also be helpful to display current scores of students as they make their progress through the page. Especially if students pass the due date.

**Comment by marklee45** [comment]
@JL248 Thank you Julia for the suggestion. I've a separate issue for that here: https://github.com/JuiceMind/JuiceMind/issues/416

Let me know if there's anything I should add to it!

**Comment by marklee45** [comment]
@mrlo-codes Mr. Lo, Yes good idea! Please let me know if this is what you're asking for: https://github.com/JuiceMind/JuiceMind/issues/417

**Comment by mrlo-codes** [comment]
@marklee45 Yep that pretty much sums it up.
