### ISSUE TITLE
AP CSA turtle class doesn't work

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#469]
However, it seems to be fine outside of AP CSA

![Image](https://github.com/user-attachments/assets/af47a8b3-1879-439c-ab40-6651b15b9a36)

**Comment by mrlo-codes** [comment]
It could be possible that the import statements aren't actually importing the packages at all. I'm also having the same issue as it is reported by multiple students. The issue seems to have started since last night.

**Comment by juicemind-dev** [comment]
Should be fixed

**Comment by warezone** [comment]
I just tried to the turtle class with CSA course and get error messages. 2.1 and 2.2 in Unit 2 are examples of the problem.

**Comment by mrlo-codes** [comment]
@warezone May you create a new issue and describe what error message occurs?
