### ISSUE TITLE
CSA section 2.5

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#476]
![Image](https://github.com/user-attachments/assets/6379074f-772a-4062-9580-cfca29633355)

**Comment by guido-ferraro** [comment]
From https://runestone.academy/ns/books/published/csawesome/Unit2-Using-Objects/topic-2-5-methods-return.html#summary
![Image](https://github.com/user-attachments/assets/5fb34c0f-d311-42c1-994b-098834ec5dad)

From ours:
![Image](https://github.com/user-attachments/assets/aeb4529d-d019-49ec-b657-3f9dc3c73a68)

**Comment by guido-ferraro** [comment]
@marklee45 this is partially solved, as the data was updated, but there's still a missing option, maybe this isn't an issue to be solved, but rather to lower the severity

**Comment by marklee45** [comment]
@guido-ferraro thanks guido

**Comment by marklee45** [comment]
moving to slack
