### ISSUE TITLE
"Intro To Python" course - multiple choice issues

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#513]
Teacher's perspective:

https://github.com/user-attachments/assets/66c7d861-3fb1-409d-a2da-2f95086319ce

Student's perspective:

https://github.com/user-attachments/assets/1fda42f6-0e6f-4a31-a684-8d81dd54e620

**Comment by guido-ferraro** [comment]
@marklee45 this should be fixed

**Comment by marklee45** [comment]
@guido-ferraro nice! when do you think it'll be pushed?

**Comment by guido-ferraro** [comment]
@marklee45 it's already in prod

**Comment by marklee45** [comment]
@guido-ferraro is it going to need a page update?

**Comment by guido-ferraro** [comment]
@marklee45 it shouldn't, but doesn't hurt. Let me know if you don't get the fix to investigate

**Comment by guido-ferraro** [comment]
@marklee45 actually, you need to refresh the browser
