### ISSUE TITLE
group project spins indefinitely and there was no prompt to "generate starter code"

### ISSUE THREAD

**Issue by marklee45** [JuiceMind/JuiceMind#520]
https://play.juicemind.com/dashboard/teams/kGax6F44IaPa0Iljj22S/item/1148d56c-63a3-4136-9c12-aea48df17d8d

https://github.com/user-attachments/assets/eaff7816-7d16-4b75-8222-fcb9353febd3

**Comment by juicemind-dev** [comment]
Should be fixed as of 9/24/2024
