### ISSUE TITLE
Collapsible Sections in Lessons

### ISSUE THREAD

**Issue by barrcs** [JuiceMind/JuiceMind#61]
To add/hide "hints" and simplify sections of lessons, it would be nice to have the option to collapse some of the sections.

**Comment by juicemind-dev** [comment]
Hi @barrcs! Thanks so much for submitting this new feature request!

I want to make sure that we fully understand your request before implementing it. Do you mean that you would want to be able to hide certain content within the actual lesson (the red section I've outlined in the image below), or you would just like to hide full pages (which you can actually do by unpublishing as seen in the purple outline)?

<img width="770" alt="image" src="https://github.com/JuiceMind/JuiceMind/assets/170696439/3c32a872-d3d6-4df0-924f-258bebc7281c">

**Comment by barrcs** [comment]
@juicemind-dev Certain content within a lesson. It helps when things get too lengthy... for instance if I wanted to add collapsed FAQs or have hints hidden but available when students need a little extra help.

**Comment by juicemind-dev** [comment]
Ahh ok got it. 

Just brainstorming here - do you think we should add a "collapse" component where you'd place everything you'd want collapsible in there, or you'd want certain components like the IDE to be collapsible by default?

**Comment by barrcs** [comment]
A collapsed component would add flexibility. An option to have it collapsed by default would be ideal.

**Comment by juicemind-dev** [comment]
Ok perfect. I've added this issue to our roadmap. You'll see updates to it as we complete this request!
