### ISSUE TITLE
Unable to overwrite existing files in Python

### ISSUE THREAD

**Issue by janesuede** [JuiceMind/JuiceMind#623]
Good morning. With python code, I can create and write to a new file as expected using 'w' mode; but if the file already exists, the file is not overwritten as expected. Do you have any suggestions?

-------------------------------------------
Good Morning! Any progress on appending/overwriting files?

**Comment by marklee45** [comment]
@Bpyoung64

**Comment by marklee45** [comment]
duplicate issue
