### ISSUE TITLE
Change lesson in left panel and doesn't change lesson displayed

### ISSUE THREAD

**Issue by kylejramstad** [JuiceMind/JuiceMind#67]
When switching between two different lessons, the lesson doesn't actually change. The URL changes, the title on the page changes, but the content of the lesson does not change. It is as if one lesson has overridden the other and now there are two copies and one lesson is just gone.
<img width="1261" alt="Screen Shot 2024-05-29 at 3 43 12 PM" src="https://github.com/JuiceMind/JuiceMind/assets/25439621/e7d0c2ec-1d40-486d-980c-c312579d13b1">
<img width="1270" alt="Screen Shot 2024-05-29 at 3 43 25 PM" src="https://github.com/JuiceMind/JuiceMind/assets/25439621/b66fb2fc-8df6-42b8-893f-19fcbc162822">

**Comment by juicemind-dev** [comment]
Hi Kyle,

This issue was present for about 2-3 hours last Friday, and I think, unfortunately, you were on the website at the wrong time and it overrode this page. 

We will recover your pages now. Could you let me know if the page you have in the screenshot is the only page which got overridden?

**Comment by kylejramstad** [comment]
The pages in the screenshot have not been recovered and I have a similar problem in my other classes lessons as well.

**Comment by juicemind-dev** [comment]
Yes, sorry we were waiting for you to confirm which pages needed to be recovered. Could you also list the other pages that need to be recovered?

**Comment by kylejramstad** [comment]
The If Else page shows the Variables page by mistake. See my original screenshot for this.
Then in my AP CSP team, the Lists lesson is mistakenly showing the Function/Subroutines lesson.

**Comment by juicemind-dev** [comment]
Ok got it. We will try to recover it now.

**Comment by juicemind-dev** [comment]
Hi Kyle, can you check if it looks like your  lessons are recovered?

**Comment by kylejramstad** [comment]
It is looking good now. Thank you.

**Comment by juicemind-dev** [comment]
Great! We also found a way to recreate this issue yesterday and pushed out a fix last night. Hopefully this will not happen again.
