### ISSUE TITLE
Clicking "My account" is a little bit slow

### ISSUE THREAD

**Issue by mark-juicemind** [JuiceMind/JuiceMind#68]
Clicking on  ![Image](https://github.com/JuiceMind/JuiceMind/assets/170837121/7dbb29db-cccf-404f-9b07-88982084402b) is a little bit slow to bring up the menu. Same issue when clicking away to close the menu.

**Comment by juicemind-dev** [comment]
Thanks Mark. We will look into this efficiency issue and update this issue accordingly.

**Comment by juicemind-dev** [comment]
I think we established that this is not an issue and it is the expected behavior. Can reopen if we think it is an issue.
