### ISSUE TITLE
Occasionally jumps to the top of the page when interacting with the IDE

### ISSUE THREAD

**Issue by juicemind-dev** [JuiceMind/JuiceMind#8]
Sometimes, in the middle of coding, the lesson plan and IDE will randomly reload and users lose some of their work.

**Comment by Guido-Ferraro** [comment]
> Occasionally jumps to the top of the page when interacting with the IDE

This seems to be related to the [default behaviour](https://mui.com/material-ui/api/modal/#:~:text=disableRestoreFocus,hidden%20or%20unmounted.) of `@mui/material` `Modal` component. When closed, it automatically shifts focus to the previously focused element, in this case, the editor which sits at the top of the page. Occurrences noted and covered were replicated by closing, canceling and submitting inside the modal component `CreateProjectModal`. 

Consider setting `disableRestoreFocus={true}` for modals opened from components larger than the viewport.

This is probably an unrelated issue and needs to be replicated consistently:
> Sometimes, in the middle of coding, the lesson plan and IDE will randomly reload and users lose some of their work.

**Comment by guido-ferraro** [comment]
Missing fix was noted for the tests Modal. Will create new PR.
