### ISSUE TITLE
IDE overlaps existing content when files tab contains many files

### ISSUE THREAD

**Issue by mrlo-codes** [JuiceMind/JuiceMind#81]
<img width="792" alt="image" src="https://github.com/JuiceMind/JuiceMind/assets/55058939/7cc9e344-9723-4a03-8ec8-d42f9665f2ed">

In the example case of PictureLab - Exploring a Picture, when clicking on the Files menu to expand the list of files, the IDE expanded to display the files listed but ends up spilling over onto other elements on the page. May be better to show the list as a scroll down when max size of element is reached.

**Comment by juicemind-dev** [comment]
Hi Mr. Lo!

Thanks so much for reporting this bug. We've been able to recreate this issue on our side and have added it to our roadmap for today. We will update this issue once it's completed.

**Comment by juicemind-dev** [comment]
We've fixed the issue with the latest push.
