### ISSUE TITLE
Multi-select for multiple page deletion or publishing toggle

### ISSUE THREAD

**Issue by mrlo-codes** [JuiceMind/JuiceMind#82]
<img width="274" alt="image" src="https://github.com/JuiceMind/JuiceMind/assets/55058939/49b81d9b-da71-448a-a419-eabbdec79449">

On teams pages are currently selected and acted on individually. If multiple pages need deleting, multiple selections are desired to avoid having to go to each and every page to delete. I'm aware that entire sections can be deleted, but this feature request is desired for individual page selections across different sections.

In addition, this same feature can be extended for publishing pages. Currently, I have to go through every single page to un-publish. Maybe add an option to sections to allow entire sections to be published/un-published?

**Comment by juicemind-dev** [comment]
Hi Mr. Lo,

This is a great feature request. We've added it to our roadmap and we will update this issue once we have completed it/have a completion date for it.

**Comment by mrlo-codes** [comment]
Looks like the feature is live!
