### ISSUE TITLE
First time writing in the IDE in a lesson results in the first letter writing somewhere else randomly on the page

### ISSUE THREAD

**Issue by juicemind-dev** [JuiceMind/JuiceMind#88]

**Comment by guido-ferraro** [comment]
It was also discussed during the daily standup an issue related to the JuiceMind IDE component button with label `Initialize JuiceMind IDE` not working on first click. It will be fixed alongside the title issue on the same branch.

**Comment by marklee45** [comment]
@juicemind-dev this is fixed right. I don't see the issue on my end
