### ISSUE TITLE
Add fullscreen option for Display panel

### ISSUE THREAD

**Issue by mrlo-codes** [JuiceMind/JuiceMind#90]
<img width="571" alt="image" src="https://github.com/JuiceMind/JuiceMind/assets/55058939/604c301a-b83d-4521-bdde-365e737a0300">

Currently, fullscreen option applies to entire IDE. Especially for Picture Lab, a fullscreen option for the display (also a plus if there is an option to open in a new window) would be super helpful to see the results. See red box for possible placement.

Separately, a request to have output terminal screen to the side of the Display panel as an option is appreciated.

**Comment by juicemind-dev** [comment]
Yes, very good point. This is related to #55  but with the addition of adding a fullscreen option for just the display. We will have this one completed soon, it's high on our priority list.

**Comment by juicemind-dev** [comment]
Completed. There is now a show display button and then click the full screen icon:


![Image](https://github.com/JuiceMind/JuiceMind/assets/170696439/bbc8ba0e-d197-4b5a-8230-721e9c10a8e8)


![Image](https://github.com/JuiceMind/JuiceMind/assets/170696439/298e8dbf-c5ea-4362-9e89-be6bb9028cdf)
