### ISSUE TITLE
DEV | Join Quiz | Clicking on the highlighted space....cross button clicks automatically 

### ISSUE THREAD

**Issue by usmaann1** [JuiceMind/JuiceMind#923]
![image](https://github.com/user-attachments/assets/84ac72d1-4b07-499a-b380-d7c1f78b3883)

**Comment by usmaann1** [comment]
@juicemind-dev , When clicking on the middle of the button, the student should not be removed.
https://www.loom.com/share/e8223e7f78b448dd9469093e79c507bc

**Comment by juicemind-dev** [comment]
This is expected behavior
